added single article components
MolchanovaA/news-fe pull request #2
Opened 2023-12-11 15:48 UTC by MolchanovaA

2023-12-11 16:58 UTC, nc-verity-gregory approved these changes
Functionally this is great,  a single article is rendered very nicely. I'm not sure why your url is including /api/ however.

You don't need to handle your dates in state, you can absolutely handle the date before you hand it to the article state.

2023-12-11 16:58 UTC, nc-verity-gregory commented on src/components/SingleArticle.jsx
> +  const [date, setDate] = useState("");
Does this really need state??

2023-12-11 16:58 UTC, nc-verity-gregory commented on src/components/SingleArticle.jsx
> +      setDate(dateCreated[0]);
There is a better way of handling dates, take a look at day.js or update the object before setting it in state as you have access to it.

2023-12-11 16:58 UTC, nc-verity-gregory commented on src/components/routes/RutesComponent.jsx
> +          <Route path="api" element={<TemplateBody />} />
What is this route doing? Why would there be a path to api?

2023-12-12 11:17 UTC, popatre requested changes
These routes still aren't quite right. You url has /api in it. You're not building an api, you're building a website so the urls don;t really make sense

2023-12-12 11:17 UTC, popatre commented on src/components/routes/RutesComponent.jsx
> +      </Routes>
These routes still aren't quite right. You url has /api in it. You're not building an api, you're building a website so the urls don;t really make sense

2023-12-12 11:37 UTC, nc-verity-gregory commented
Nicely done, don't forget to put a loading pattern in on this. You don't need to resubmit that though :) just on a slow connection it isn't clear that its working.

2023-12-12 11:39 UTC, merged